baseURL: https://isahelen-chen.netlify.app/
languageCode: en-us
title: Isa_Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I am an optimstic girl who loves traveling, art history, dancing and exploring for new things. I have lived in three continents in the world. Currently, I'm on my way of becoming a great future banker. ^ ^ One fun fact about me is that I am a certificated scuba diver! Yay~
      Welcome to my page!
    title: Hi, my name is Isahelen
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ichen.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (777) 999-0000 （Don't call. It's fake lol)
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Isahelen C.
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
    #    label: Twitter
     #   url: https://www.twitter.com
    #   - icon: fa-facebook
    #    label: Facebook
    #   url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Isahelen
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/fuyang-isahelen-chen/
  image: ''
  name: Isahelen
  navigation:
    button1:
      - name: Get Started
        url: blogs
    #button2:
     # - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
       # url: elements.html
    menu: Menu
    subtitle: Personal Website
    title: Isahelen 
  tiles:
    enable: yes
    showcase:
      - image: LBS.jpg
        subtitle: I am a current LBS student
        title: Self-Introduction
        url: blogs/LBS
      - image: LifeExpectancy.jpg
        subtitle: Life Expectancy Among Countries
        title: Life Expectancy
        url: blogs/LifeExpectancy
      - image: MyPet.jpg 
        subtitle: His name is Prince! He is very cute, isn't he? :)
        title: My Pet
        url: blogs/mypet
      - image: barcelona.jpg
        subtitle: Bienvenidos a Barcelona!
        title: Barcelona AirBnb Case Study
        url: blogs/barcelona
    #  - image: pic05.jpg
    #    subtitle: Ipsum Dolor Sit Amet
    #    title: Consequat
    #    url: blogs/ipsum
    #  - image: pic06.jpg
    #    subtitle: Feugiat Amet Tempus
    #    title: Etiam
    #    url: blogs/ipsum

  two:
    buttonText: Get Started
    enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #    \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #    condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #    pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #    Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #    amet pharetra et feugiat tempus."
  #  title: Beautiful Life
  #  url: blogs
